name: ClearLag
version: 1.0
main: com.azli.clearlag.ClearLag
author: Azli
commands:
  clearlag:
    description: Clears dropped items to reduce lag after a set time.
    usage: /clearlag <minutes>
    permission: clearlag.command
  clearlagreload:
    description: Reloads the ClearLag plugin configuration.
    usage: /clearlagreload
    permission: clearlag.reload
permissions:
  clearlag.command:
    description: Allows the use of the /clearlag command.
    default: op
  clearlag.reload:
    description: Allows the use of the /clearlagreload command to reload plugin configuration.
    default: op